# argocd-values.yaml
# Enable metrics for controller, server and repo-server
controller:
  metrics:
    enabled: true

server:
  metrics:
    enabled: true
  # change service.type if you want external access
  service:
    type: ClusterIP

repoServer:
  metrics:
    enabled: true
